# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 333a39b71e964ff2c192e5f1a92eef00165d2afd02289be87d25aad1f0a4d4c1065a7461d77ade2c4cb083218d8f005c08472fcaf8084f06519212dff46c3da4

test:
  secret_key_base: 73e5a13605f8d84dd72f7d84797969531185d8e25309877ae868246b8394652b054bf41181e8a917599c6ca0d7b417583b2e78bccdcfa98f7b6f25320e39a46b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
